service: email
frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: python3.8
  stage: ${env:ENV}
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
      - sqs:ReceiveMessage
      Resource: 
        Fn::GetAtt: [ EmailQueueDemo, Arn ]
      
    - Effect: "Allow"
      Action:
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
      - sqs:ReceiveMessage
      Resource: 
        Fn::GetAtt: [ EmailQueueDemoDLQ, Arn ]

    - Effect: "Allow"
      Action:
       - ses:SendEmail
       - ses:SendRawEmail
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: EmailAttachmentMediator
            - "/*"

custom:
  config: ${file(config/env/${env:ENV}.yml)}
  pythonRequirements:
    dockerizePip: true
  logRetentionInDays: 30


functions:
  main-handler-py:
    handler: src/email/handler.email_handler
    name: ${self:service}-main-handler-py
    timeout: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EmailQueueDemo
              - Arn
          batchSize: 1
  fallback-handler-py:
    handler: src/email/handler.email_handler_fallback
    timeout: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EmailQueueDemoDLQ
              - Arn
          batchSize: 1

resources:
  Resources:
    EmailQueueDemo:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "EmailQueueDemo"
        MessageRetentionPeriod: 1209600 # 14 days in seconds
        VisibilityTimeout: 60
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - EmailQueueDemoDLQ
              - Arn
          maxReceiveCount: 2
    EmailQueueDemoDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "EmailQueueDemoDLQ"
        MessageRetentionPeriod: 1209600 # 14 days in seconds
        VisibilityTimeout: 90
    EmailAttachmentMediator:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "email-attachment-mediator"
        LifecycleConfiguration:
          Rules:
          - Id: 'DefaultRule'
            Status: 'Enabled'
            ExpirationInDays: '30'